# Setup
title: Hari Krishna
tagline: "Full Stack Developer"
description: "I am a Passionate Full Stack Developer, This is my personal blog and portfolio where I share my thoughts and ideas."
url: https://hari-krishna-tech.github.io/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Hari Krishna T
  url: https://www.linkedin.com/in/hari-krishna-b731601b1/
  email: harikrishna03902@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
